services:
  demoname-backend:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile.backend
    image: imagename-backend:latest
    environment:
      - GROVE_API_KEY=${GROVE_API_KEY}
      - GROVE_BASE_URL=${GROVE_BASE_URL}
      - GROVE_CHAT_MODEL=${GROVE_CHAT_MODEL}
    ports:
      - "8080:8080"
    restart: always
    container_name: demoname-backend