env:
  NODE_ENV: prod
  GROVE_BASE_URL: https://grove-gateway-prod.azure-api.net/grove-foundry-prod/anthropic
  GROVE_CHAT_MODEL: claude-haiku-4-5

envSecrets:
  GROVE_API_KEY: contentlab-chat

serviceAccount:
  enabled: true
  irsa:
    accountId: "275662791714"
    roleName: "kanopy-prod-cicd-irsa"

security:
  dataClassification: "Internal"
  dataDesignation: ["MI"]

ownership:
  driEmail: "benjamin.lorenze@mongodb.com"
