env:
  NODE_ENV: prod
  GROVE_BASE_URL: https://grove-gateway-prod.azure-api.net/grove-foundry-prod/anthropic
  GROVE_CHAT_MODEL: claude-haiku-4-5

envSecrets:
  MONGODB_URI: contentlab-chat
  DATABASE_NAME: contentlab-chat
  APP_NAME: contentlab-chat
  USER_PROFILES_COLLECTION: contentlab-chat
  NODE_ENV: contentlab-chat
  GROVE_API_KEY: contentlab-chat

security:
  dataClassification: "Internal"
  dataDesignation: ["MI"]

ownership:
  driEmail: "benjamin.lorenze@mongodb.com"
