env:
  NODE_ENV: staging

envSecrets:
  MONGODB_URI: contentlab-chat
  DATABASE_NAME: contentlab-chat
  APP_NAME: contentlab-chat
  AWS_REGION: contentlab-chat
  USER_PROFILES_COLLECTION: contentlab-chat
  NODE_ENV: contentlab-chat
  BEDROCK_MODEL_HAIKU: contentlab-chat

serviceAccount:
  enabled: true
  irsa:
    accountId: "275662791714"
    roleName: "kanopy-staging-cicd-irsa"

security:
  dataClassification: "Internal"
  dataDesignation: ["MI"]

ownership:
  driEmail: "benjamin.lorenze@mongodb.com"
