# ---chat_completions.py---

# This file contains the GroveAnthropicChatCompletions class, which is used to generate
# chat completions using Anthropic Claude models served through MongoDB's Grove gateway.

# Importing necessary libraries
import logging
import os
import time
from typing import Optional

import httpx
from dotenv import load_dotenv

load_dotenv()

# Setting up logging
logger = logging.getLogger(__name__)

# Grove configuration defaults. All of these can be overridden via environment variables.
DEFAULT_GROVE_BASE_URL = "https://grove-gateway-prod.azure-api.net/grove-foundry-prod/anthropic"
DEFAULT_GROVE_CHAT_MODEL = "claude-haiku-4-5"
ANTHROPIC_VERSION = "2023-06-01"

# `max_tokens` was previously hardcoded to 512 under Bedrock, which silently truncated
# responses (most notably the strict-JSON output expected by `proofread_content`, which
# falls back to an empty result on a JSON parse error). 4096 gives the model enough room
# to complete its response without truncation.
DEFAULT_MAX_TOKENS = 4096
DEFAULT_TEMPERATURE = 0.00001

REQUEST_TIMEOUT_SECONDS = 30.0
MAX_RETRIES = 3
RETRY_BACKOFF_SECONDS = 1.0

# Errors are only worth retrying if they're transient (timeouts, connection issues, or
# server-side 5xx responses). Client errors (4xx, e.g. bad auth or a malformed request)
# won't resolve themselves on retry.
RETRYABLE_EXCEPTIONS = (httpx.TimeoutException, httpx.ConnectError, httpx.ReadError)


class GroveAnthropicChatCompletions:
    """A class to generate chat completions using Anthropic Claude models via MongoDB's Grove gateway."""

    # Reference: Grove exposes the Anthropic Messages API shape behind Azure APIM.
    log: logging.Logger = logging.getLogger("GroveAnthropicChatCompletions")

    def __init__(
        self,
        api_key: Optional[str] = None,
        base_url: Optional[str] = None,
        model: Optional[str] = None,
        timeout: float = REQUEST_TIMEOUT_SECONDS,
        max_retries: int = MAX_RETRIES,
    ) -> None:
        """
        Initialize the GroveAnthropicChatCompletions class.

        Args:
            api_key (str): The Grove API key. Default is os.getenv("GROVE_API_KEY").
            base_url (str): The Grove gateway base URL. Default is os.getenv("GROVE_BASE_URL").
            model (str): The Anthropic model id to use. Default is os.getenv("GROVE_CHAT_MODEL").
            timeout (float): Request timeout in seconds.
            max_retries (int): Number of attempts made for a single `predict` call before raising.
        """
        self.api_key = api_key or os.getenv("GROVE_API_KEY")
        self.base_url = (base_url or os.getenv("GROVE_BASE_URL", DEFAULT_GROVE_BASE_URL)).rstrip("/")
        self.model = model or os.getenv("GROVE_CHAT_MODEL", DEFAULT_GROVE_CHAT_MODEL)
        self.timeout = timeout
        self.max_retries = max_retries

        if not self.api_key:
            self.log.warning("GROVE_API_KEY is not set; requests to Grove will fail authentication.")

    def predict(self, text: str) -> str:
        """Predict a chat completion based on the input text.

        Args:
            text (str): The input text to generate a chat completion for.

        Returns:
            str: The chat completion generated by the model.

        Raises:
            RuntimeError: If Grove cannot be reached, returns an error status, or returns a
                response body that doesn't match the expected Anthropic Messages API shape.
        """
        url = f"{self.base_url}/v1/messages"

        # Grove sits behind Azure APIM, which authenticates with `api-key`, NOT Anthropic's
        # native `x-api-key` header. Getting this wrong is the most common failure mode.
        headers = {
            "api-key": self.api_key,
            "anthropic-version": ANTHROPIC_VERSION,
            "content-type": "application/json",
        }

        # Note: unlike Bedrock's native request body, there is no `anthropic_version` field
        # here -- that moved to the `anthropic-version` header above.
        payload = {
            "model": self.model,
            "max_tokens": DEFAULT_MAX_TOKENS,
            "temperature": DEFAULT_TEMPERATURE,
            "messages": [
                {
                    "role": "user",
                    "content": [{"type": "text", "text": text}],
                }
            ],
        }

        last_error: Optional[Exception] = None

        for attempt in range(1, self.max_retries + 1):
            try:
                response = httpx.post(url, headers=headers, json=payload, timeout=self.timeout)
                response.raise_for_status()
                body = response.json()
                return body["content"][0]["text"]

            except RETRYABLE_EXCEPTIONS as e:
                last_error = e
                self.log.warning(
                    f"Grove request attempt {attempt}/{self.max_retries} timed out or failed to connect: {e}"
                )

            except httpx.HTTPStatusError as e:
                last_error = e
                if e.response.status_code >= 500 and attempt < self.max_retries:
                    self.log.warning(
                        f"Grove request attempt {attempt}/{self.max_retries} got server error "
                        f"{e.response.status_code}: {e}"
                    )
                else:
                    # Client errors (auth, bad request, etc.) won't be fixed by retrying.
                    self.log.error(f"ERROR: Can't invoke Grove model '{self.model}'. Reason: {e}")
                    raise RuntimeError(
                        f"Grove request to model '{self.model}' failed with status "
                        f"{e.response.status_code}: {e}"
                    ) from e

            except (KeyError, IndexError, ValueError) as e:
                # Response came back but didn't match the expected Anthropic Messages API shape.
                self.log.error(f"ERROR: Unexpected response shape from Grove model '{self.model}'. Reason: {e}")
                raise RuntimeError(f"Unexpected response shape from Grove model '{self.model}': {e}") from e

            if attempt < self.max_retries:
                time.sleep(RETRY_BACKOFF_SECONDS * attempt)

        self.log.error(
            f"ERROR: Can't invoke Grove model '{self.model}' after {self.max_retries} attempts. Reason: {last_error}"
        )
        raise RuntimeError(
            f"Failed to get a response from Grove model '{self.model}' after {self.max_retries} attempts: {last_error}"
        ) from last_error
